### ISSUE TITLE
Bid response not containing CPM should emitStatsEvent of hs_slot_pass 

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/criteo-adapter#1]
Hi, 

When the Criteo adapter returns no CPM, we were informed that this should be treated with the wrapper as a 'no-bid' event rather than 'error'.

Can this be updated here: https://github.com/indexexchange/criteo-adapter/blob/master-v2/criteo-htb.js#L113 so that the wrapper can handle the correct event for reporting?

Thanks

**Comment by Spark-NF** [comment]
@ix-certification this issue mentions "no CPM" but your link (as well as the only possible source of an 'error' event) is for "no slots". Also, no CPM responses seem to be properly handled:

https://github.com/indexexchange/criteo-adapter/blob/3ec8bd2d86359f88ee5914f2e286b3a91634247b/criteo-htb.js#L160-L165

Can you confirm you're talking about missing **slots**, and that it is therefore fixed by PR #2?

Just to clarify, we're differentiating 4 valid cases:
- HTTP 204 (no content) -> no bid
- HTTP 200 without slots -> no bid
- HTTP 200 with slots without CPM -> no bid
- HTTP 200  with slots with CPM -> bid

**Comment by ix-certification** [comment]
@Spark-NF 
Yes, this ticket was specifically to address the 2nd case here i.e. "HTTP 200 without slots -> no bid"
